app/urls.py
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.loginview, name="login"),
    path('welcome/', views.welcome, name="welcome"),
    path('contact/', views.contact_us, name="contact"),
    path('profile/', views.profile, name="profile"),
    path('about/', views.about_us, name="about"), 
    path('history/', views.history, name="history"),
    path('ref_num/', views.momo_ref_confirm, name="momo_ref_confirm"),
    path('logout/', views.logout_view, name="logout"),
]

eblogchain/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about_us.html
{% extends "base.html" %}

{% load static %}

{% block title %}Welcome {% endblock %}


{% block main %}
<div class="container">
    <section class="bg-white shadow-sm">
        <div class="container">
            <div class="flex-row flex-center t-center">

                <div class="w-50 p-2">
                    <h3>Mission</h3><hr>
                    <p>We day to day put a smile on your face with just an alert.</p>
                </div>
                <div class="w-50 p-2">
                    <h3>Vison</h3><hr>
                    <p>Provide a 360 service to overcome your financial onus. We endeavor to make our clients happy</p>

                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

templates/base.html
{% extends "base1.html" %}

{% load static %}

{% block extraoverlayclass %}
max-height-70vh
{% endblock %}


{% block extraimagebackgroundclass %}
max-height-70vh
{% endblock %}


{% block content %}

<div class="flex-col flex-center">
    <nav class="header-nav">
        <ul class="flex-row flex-center ">
            <li {% if "welcome" in request.path %}class="selected" {% endif %}>
                <a href="{% url 'app:welcome' %}">
                    <div class="image-icon">
                        <img src="{% static 'img/home-icon.png' %}">
                    </div>
                    <h6>Welcome</h6>
                </a>
            </li>
            <li {% if "profile" in request.path %}class="selected" {% endif %}>
                <a href="{% url 'app:profile' %}">
                    <div class="image-icon">
                        <img src="{% static 'img/profile-icon1.png' %}">
                    </div>
                    <h6>Profile</h6>
                </a>
            </li>
            <li {% if "about" in request.path %}class="selected" {% endif %}>
                <a href="{% url 'app:about' %}">
                    <div class="image-icon">
                        <img src="{% static 'img/about-icon.png' %}">
                    </div>
                    <h6>About Us</h6>
                </a>
            </li>
            <li {% if "history" in request.path %}class="selected" {% endif %}>
                <a href="{% url 'app:history' %}">
                    <div class="image-icon">
                        <img src="{% static 'img/history-icon.png' %}">
                    </div>
                    <h6>History</h6>
                </a>
            </li>
            <li {% if "contact" in request.path %}class="selected" {% endif %}>
                <a href="{% url 'app:contact' %}">
                    <div class="image-icon">
                        <img src="{% static 'img/contact-icon.png' %}">
                    </div>
                    <h6>Contact Us</h6>
                </a>
            </li>
        </ul>
    </nav>
    {% block main %}

    {% endblock %}
    {% block footer %}
    <footer>
            <p> &copy; <span>BLOGCHAIN</span> 2019.</p>
    </footer>
    {% endblock %}
</div>
    {% endblock %}

templates/base1.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

    </head>
    <body>
        <div class="overlay {% block extraoverlayclass %}{% endblock %}">

        </div>
        {% if messages %}
        <div class="messages-overlay">
            <div class="messages">
                <p class="close">x</p>
                <div class="messages-list">
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <li class="error">{{ message }}</li>
                    {% else %}
                        <li>{{ message }}</li>
                    {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="img-background {% block extraimagebackgroundclass %}{% endblock %}">
            <img src="{% static 'img/bg1.jpg' %}">
        </div>


        {% block content %}

        {% endblock %}
        {% block footer %}
        {% endblock %}
        <script src="{% static 'js/moneysite.js' %}"></script>
    </body>
</html>

templates/contact_us.html
{% extends "base.html" %}

{% load static %}

{% block title %}Welcome {% endblock %}


{% block main %}
<div class="container">
    <section class="bg-white shadow-sm">

<div class="flex-row flex-center">

        <form class="flex-col flex-center  w-50" method="post" action=".">
            <h3>Contact us via</h3>
            {% csrf_token %}
            {% if contact_form.errors %}
                <p>{{ contact_form.errors }}</p>
            {% endif %}
            {% for field in contact_form %}
            <p> <sub class="error">{{ field.errors }}</sub>{{ field }}</p>
            {% endfor %}

            <p class="m-0">
                <input type="submit" value=">">
            </p>
        </form>
        <div class="contact-links">

            <div class="flex-col flex-center">
                    <h3>Or contact us through</h3>
                <ul class="flex-row flex-center">
                    <li>
                        <a href="#">
                            <img src="{% static 'img/Whatsapp-3.png' %}">
                            <h6>Whatsapp</h6>
                        </a>
                    </li>
                    <li>
                            <a href="#">
                                <img src="{% static 'img/telegram.png' %}">
                                <h6>Telegram</h6>
                            </a>
                        </li>
                        <li>
                                <a href="#">
                                    <div class="image-icon"><img src="{% static 'img/twitter.png' %}"></div>
                                    <h6>Twitter</h6>
                                </a>
                            </li>
                            <li>
                                    <a href="#">
                                        <img src="{% static 'img/facebook.png' %}">
                                        <h6>Facebook</h6>
                                    </a>
                                </li>
                </ul>
            </div>
        </div>
    </div>
</div>
    </section>
</div>
{% endblock %}

templates/history.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}History {% endblock %}


{% block main %}
<div class="container">

    <section class="bg-white shadow-sm">
        <div class="history-main flex-col">
            <div class="flex-row flex-center history-links">
                <a href="#1" id="history-link1" class="history-bg-white">PLEDGE</a>
                <a href="#1" id="history-link2">PENDING</a>
                <a href="#1" id="history-link3">RECEIVED</a>
            </div>
            <div id="history-items">
                <div class="history-item flex-col flex-center">
                    {% if request.user.profile.has_unconfirmed_ref_number %}
                    {% for pledge in request.user.profile.pledges.all %}
                    {{ pledge }}
                    {% endfor %}
                        <p>{{ request.user.profile.has_unconfirmed_ref_number }} <a href="{% url 'app:momo_ref_confirm' %}" class="link">Enter Momo Reference code</a> for existing Pledge</p>
                    {% else %}
                        <form class="flex-col flex-center  w-50 m-auto" method="post" action=".">
                            <h3>Pledge</h3>

                            {% csrf_token %}
                            {% if pledge_form.errors %}
                            <p>{{ pledge_form.errors }}</p>
                            {% endif %}
                            {% for field in pledge_form %}
                            <p> <sub class="error">{{ field.errors }}</sub>{{ field }}</p>
                            {% endfor %}

                            <p class="m-0">
                                <input type="submit" value=">">
                            </p>
                        </form>
                    {% endif %}
                </div>
                <div class="history-item flex-col flex-center hidden">
                    {% if next_payment %}
                    {% if next_payment.confirm_received %}
                        <h3>Amount: GH {{ next_payment.amount }}</h3>
                        <div class="countdown">
                            <table>
                                <tr>
                                    <td colspan="4">Time to next payment</td>
                                </tr>
                                <tr>
                                    <td id="days"></td>
                                    <td id="hours"></td>
                                    <td id="minutes"></td>
                                    <td id="seconds"></td>
                                </tr>
                                <tr>
                                    <td>Days</td>
                                    <td>Hours</td>
                                    <td>Minutes</td>
                                    <td>Seconds</td>

                                </tr>
                            </table>
                        <script>
                            function countdown(){
                                var now = new Date()

                                var eventDate = new Date("{{ next_payment.payment_due|escapejs }}");
                                var currentTime = now.getTime();
                                var eventTime = eventDate.getTime();
                                var remTime = eventTime - currentTime;
                                var s = Math.floor(remTime/ 1000);
                                var m = Math.floor(s/60);
                                var h = Math.floor(m/60);
                                var d = Math.floor(h/24);
                                h %= 24;
                                m %=60;
                                s %=60;
                                h = (h<10) ? "0" + h: h;
                                m = (m<10) ? "0" + m: m;
                                s = (s<10) ? "0" + s: s;
                                document.getElementById("days").textContent = d;
                                document.getElementById("hours").textContent = h;
                                document.getElementById("minutes").textContent = m;
                                document.getElementById("seconds").textContent = s;
                                setTimeout(countdown, 1000);
                            }
                            countdown();
                        </script>
                        {% else %}
                        <h2>Please wait while our admins confirm your payment</h2>
                        {% endif %}
                        </div>
                        {% else %}
                        <h2>You do not have any pending pledges</h2>

                        {% endif %}

                </div>
                <div class="history-item flex-col flex-center hidden">
                    <div class="pledge-table-div">
                    <table class="pledge-table">
                        <thead>
                            <td>Amount(GHC)</td>
                            <td>Returns(GHC)</td>
                            <td>Date</td>
                            <td>Returns Date</td>
                            <td>Completed</td>
                        </thead>
                        {% for pledge in request.user.profile.pledges.all %}
                            {% if pledge.paid %}
                            <tr>
                                <td>{{ pledge.amount }}</td>
                                <td>{{ pledge.amount_to_pay }}</td>
                                <td>{{ pledge.date_pledged }}</td>
                                <td>{{ pledge.payment_due }}</td>
                                <td>{{ pledge.paid }}</td>
                            </tr>
                            {% else %}
                            {% if request.user.profile.pledges.all|length == 1 %}
                               <tr><td colspan='5'><h2>You have no Pledges received</h2></td></tr>
                                {% endif %}
                            {% endif %}

                        {% empty %}
                    <h2>You have no Pledges received</h2>
                    {% endfor %}

                </table>
                </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script>
    var history_link_1 = document.getElementById('history-link1');
    var history_link_2 = document.getElementById('history-link2');
    var history_link_3 = document.getElementById('history-link3');
    var history_items = document.getElementById('history-items');
    var history_items_list = history_items.children;
    var links = [history_link_1, history_link_2, history_link_3];
    history_link_1.addEventListener('click', function(e){console.log('here');e.preventDefault(); togglehidden(0);});
    history_link_2.addEventListener('click', function(e){console.log('here');e.preventDefault();  togglehidden(1);});
    history_link_3.addEventListener('click', function(e){console.log('here');e.preventDefault(); togglehidden(2);});

    function togglehidden(index){

        for (let i=0; i<links.length; i++){
            links[i].classList.remove('history-bg-white');
            history_items_list[i].classList.add('hidden');
        }
        links[index].classList.add('history-bg-white');
        history_items_list[index].classList.remove('hidden');

    }
</script>
{% endblock %}

templates/index.html
{% extends "base1.html" %}

{% block title %}
Index
{% endblock %}

{% block content %}
<div class="mid-links abs-center">
    <a href="{% url 'app:login' %}" class="button" id="loginlink">
        Log In
    </a>
    <a href="{% url 'app:signup' %}" class="button" id="signuplink">Sign Up</a>
</div>
{% endblock %}

templates/login.html
{% extends "base1.html" %}

{% block title %}
Log In
{% endblock %}

{% block content %}
<div class="p-5">
    <h1 class="page-header">Log In</h1>

<div class="flex-row flex-center">

        <form class="flex-col flex-center  w-50" method="post" action=".">
            {% csrf_token %}
            {% if login_form.errors %}
                <p>{{ login_form.errors }}</p>
            {% endif %}
            {% for field in login_form %}
            <p> <sub class="error">{{ field.errors }}</sub>{{ field }}</p>
            {% endfor %}

            <p class="m-0">
                <input type="submit" value=">">
            </p>
            <sub>Not having an account? <a href="{% url 'app:signup' %}" class="link">Sign up here</a></sub>
        </form>
    </div>
</div>
{% endblock %}

templates/momo_ref.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}History {% endblock %}


{% block main %}
<div class="container">

    <section class="bg-white shadow-sm">
        <div class="history-main flex-col">
            <div class="flex-row flex-center history-links">
                <a href="#1" id="history-link1">PLEDGE</a>
                <a href="#1" id="history-link2">PENDING</a>
                <a href="#1" id="history-link3">RECEIVED</a>
            </div>
            <div id="history-items">
                <div class="container flex-col flex-center">  
                        <form class="flex-col flex-center  w-50 m-auto" method="post" action=".">
                            <h3>Pledge</h3>
                        
                            {% csrf_token %}
                            {% if momo_ref_form.errors %}
                            <p>{{ momo_ref_form.errors }}</p>
                            {% endif %}
                            {% for field in momo_ref_form %}
                            <p> <sub class="error">{{ field.errors }}</sub>{{ field }}</p>
                            {% endfor %}
                            <p class="m-0">
                                <input type="submit" value=">">
                            </p>
                        </form>
                    {% endif %}
                </div>
               
               
            </div>
        </div>
    </section>
</div>

{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}Welcome {% endblock %}


{% block main %}
<div class="container">

    <section class="bg-white shadow-sm">
        <div class="flex-row flex-center">
            <div>
                <div class="profile-image">
                    <img src="
                        {% if request.user.profile.picture %}
                            {{ request.user.profile.picture.url }}
                        {% else %}
                            {% static 'img/profile-icon1.png' %}
                        {% endif %}
                    " alt="Profile Image"> 
                </div>
                <table class="profile-table">
                    <tr>
                        <td>Momo Name</td>
                        <td>{{ request.user.profile.momo_name }}</td>
                    </tr>
                    <tr>
                        <td>Momo Number</td>
                        <td>{{ request.user.username }}</td>
                    </tr>
                </table>
            </div>
            <form action="." method="POST" enctype="multipart/form-data" class="flex-col flex-center   w-50">
                {% csrf_token %}
                {{ profile_form.as_p }}
                <p class="m-0"><input type="submit" value=">"></p>
                <sub>Want to <a href="{% url 'app:login' %}" class="link">Change Password</a>?</sub>
            </form>
        </div>
    </section>
</div>
{% endblock %}

templates/signup.html
{% extends "base1.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<!--<div class="auth login  full-dim">
    <form class="m-auto" action="." method='post' enctype="multipart/form-data">
    -->
<div class="p-5">

    <h1 class="page-header">Sign Up</h1>
    <div class="flex-row flex-center">


        <form action="." method="POST" enctype="multipart/form-data" class="flex-col flex-center   w-50">
            {% csrf_token %}
            <p>{{ profile_form.momo_name }}</p>
            <p>{{ user_form.username }}</p>
            <p>{{ user_form.password }}</p>
            <p>{{ user_form.password2 }}</p>
            <p>{{ profile_form.picture }}</p>
            <p>{{ profile_form.date_of_birth }}</p>
            <p class="m-0"><input type="submit" value=">"></p>
            <sub>Have an account ? <a href="{% url 'app:login' %}" class="link">Log In here</a></sub>
        </form>
    </div>
</div>
{% endblock %}

templates/temp.html
<div class="col-md-12">
        <div class="col-sm-8 m-auto">
            <form class="profileform">
                <a href="#" class="close">x</a>
                <img class="round-profile-img" src="img/item-04.jpg">
                <h3>Sign Up</h3>
                <p>
                    <input type="text" placeholder="Momo Name">
                </p>
                <p>
                    <input type="tel" placeholder="Momo Number...">
                </p>
                <p>
                    <label>Gender: &nbsp;</label>
                    <select>
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </p>
                <p>
                    <input type="date" placeholder="Date of Birth">
                </p>
                <p>
                    <input type="text" placeholder="Country...">
                </p>

                <p>
                    <input type="text" placeholder="City">
                </p>
                <p>
                    <input type="submit" value=">">
                </p>
            </form>
        </div>
    </div>

templates/verification.html
{% extends "base1.html" %}

{% block title %}
Verify account
{% endblock %}

{% block content %}
<div class="p-5">
    <h1 class="page-header">Verify account</h1>

<div class="flex-row flex-center">

        <form class="flex-col flex-center w-50" method="post" action=".">
            {% csrf_token %}
            {% if verification_form.errors %}
                <p>{{ verification_form.errors }}</p>
            {% endif %}
            {% for field in verification_form %}
                <p><sub class="error">{{ field.errors }}</sub>{{ field }}</p>
            {% endfor %}
            <p class="m-0">
                <input type="submit" value=">">
            </p>
            <sub>Not having an account? <a href="{% url 'app:signup' %}" class="link">Sign up here</a></sub>
        </form>
    </div>
</div>
{% endblock %}

templates/welcome.html
{% extends "base.html" %}

{% load static %}
{% block title %}Welcome {% endblock %}


{% block extraoverlayclass %}
{% endblock %}

{% block extraimagebackgroundclass %}
{% endblock %}

{% block main %}
<div class="m-auto w-80 slider-main">
    <div class="slider-container">
        <div class="sliders w-90 p-5">
            <div class="slider-obj ">

                <p>Welcome to <span class="color-primary">BLOGCHAIN</span>. Here your money work for you.</p>
            </div>
            <div class="slider-obj">

                <p>Invest with <span class="color-primary">BLOGCHAIN</span> and gain 100% profit</p>
            </div>
            <div class="slider-obj">

                <p>Don't save money and work for money. Work <em>smart</em>, not hard.</p>
            </div>
        </div>

    </div>
    
</div>
<script>
    var slider_objs = document.getElementsByClassName("slider-obj");
    var slider_num = 0;
    var nexts = document.getElementsByClassName("next");

    for (let i = 0; i < nexts.length; i++) {
        nexts[i].addEventListener('click', function (e) {
            show_slide(1);
        });
    }
    show_slide(0);
    function show_slide(num = 1) {
        for (let i = 0; i < slider_objs.length; i++) {
            slider_objs[i].classList.add('hidden');
        }

        slider_num += num;
        if (slider_num >= slider_objs.length) {
            slider_num = 0;
        }
        else if (slider_num < 0) {
            slider_num = slider_objs.length - 1;
        }
        slider_objs[slider_num].classList.remove('hidden');
        setTimeout(show_slide, 5000);
    }

</script>
</div>
{% endblock %}

{% block footer %}{% endblock %}